# docker-compose.yml
version: '3.8'

services:
  csharp:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: csharp-dev
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true